### ISSUE TITLE
Out-of-category search results

### ISSUE THREAD

**Issue by grahamperrin** [dbaio/portsfallout#2]
Hi

<https://portsfallout.com/fallout?port=&maintainer=&env=&category=&categories=x11&flavor=> for `x11` alone currently includes _textproc/fcitx5-configtool_ from the `textproc` category …

**Comment by dbaio** [comment]
Hi.

It's because this port is also in the `x11` category.
This filter matches any category, not just the main category.

```
PORTNAME=       fcitx5-configtool
DISTVERSION=    5.0.8
CATEGORIES=     textproc x11
...
```

Take a look when you filter by the `python` category.
https://portsfallout.com/fallout?categories=python
